# Generated by Django 5.0.1 on 2024-02-21 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipe_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 2, 21, 6, 57, 37, 990590, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
