# Generated by Django 5.0.1 on 2024-02-21 07:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_recipe_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="images",
            new_name="cover_image",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 2, 21, 7, 46, 21, 71700, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.TextField()),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipes.recipe"
                    ),
                ),
            ],
        ),
    ]
