# Generated by Django 5.0.1 on 2024-02-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_uploadedfile_alter_image_recipe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.ImageField(upload_to=""),
        ),
    ]
